#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_DEVICE_ID              "RA8P1-RF-EDGE-001"

#define APP_SECTOR_COUNT           3U
#define APP_DETECT_PERIOD_MS       250U
#define APP_HEARTBEAT_PERIOD_MS    500U

#define APP_TELEMETRY_TRANSPORT_CONSOLE  0U
#define APP_TELEMETRY_TRANSPORT_UDP      1U
#define APP_TELEMETRY_TRANSPORT          APP_TELEMETRY_TRANSPORT_CONSOLE

#define APP_RSSI_SCALE             1024U
#define APP_KURTOSIS_SCALE         256U

#define APP_SCORE_THRESHOLD_Q10    1536U
#define APP_CONFIRM_REQUIRED       3U
#define APP_ALERT_COOLDOWN_TICKS   24U
#define APP_STREAK_DECAY_Q4        8U
#define APP_STREAK_UNIT_Q4         16U

#define APP_TELEMETRY_CENTER_HOST  "192.168.31.100"
#define APP_TELEMETRY_CENTER_PORT  9000U

#endif


